development/code-reviews.md

This documentation came from a discussion at one of our developer get-togethers and is an initial attempt to document how we want code reviews to work within our team.

Add documentation on how we do code reviews

---

development/code-reviews.md

Part of https://github.com/alphagov/design-system-team-internal/issues/424
Replace references to `master` to `main`.
Part of our work to rename the default branches in our repos from `master` to `main`.

Replace references to master with main

---

development/code-reviews.md

Adding some information about how to review Dependabot PRs.
The rest of the doc could possibly do with a bit of restructuring now, but we could do that in a separate PR if we thought it was useful.

Add information about reviewing Dependabot PRs

---

config/tech-docs.yml
source/stylesheets/screen.css.scss

Our team docs won’t be hosted on a service domain (at least not initially) so we should avoid using the logo or font.
Remove the logo (but add GOV.UK back to the name) and switch out the font.

Remove the GOV.UK crown and font

---

README.md
config/tech-docs.yml

Thanks to @36degrees adding Netlify to this repo, we can now view the playbook at https://govuk-design-system-team-docs.netlify.app/

Update canonical URL

---

source/how-we-work/version-control/pull-requests.html.md

Dependabot seems to easily promote some of our `devDependencies` to `dependencies` in `package-lock.json`. This usually happens for our dependencies listed as `optionalDependencies` and can be easily fixed. 
This PR documents the situation and the fix in our process for reviewing Dependabot PRs.
https://deploy-preview-37--govuk-design-system-team-docs.netlify.app/how-we-work/version-control/pull-requests#reviewing-a-pr-from-dependabot

Add note about Dependabot promoting some of our dependencies

---

source/index.html.md.erb

This should make it easier for folks to find out how to add to the playbook, as we mostly link to the built version of the playbook rather than the repo.

Add contribution guide to index

---

source/how-we-work/index.html.md

Link to guide to get help from other roles was broken.

Fix link in 'How we work' section

---

source/development/feature-flags.html.md

What it says on the tin. Fixes https://github.com/alphagov/design-system-team-docs/issues/47

Add docs for using feature flags in govuk-frontend

---

source/guides/index.html.md
source/how-we-work/contribution-model.html.md.erb

In one-to-one sessions with team members, our coach identified that people needed more clarity on their role in the team.
Specifically:
- What is expected of me in my role?
- What should or shouldn’t I get involved in?
- When should I get involved?
The team reviewed the [capability framework](https://ddat-capability-framework.service.gov.uk/) for their role to get a general overview. We then mapped what each role contributes to new elements in our contribution model, and what each role needed from others on the team to be successful. 
This pull request makes those roles and responsibilities a part of our playbook.

Add roles and responsibilities

---

source/who-we-are/index.html.md.erb
source/who-we-are/leadership-group.html.md

Includes information on who is in the group, what the group does, and the agreed leadership charter.

Add leadership group documentation

---

config/tech-docs.yml
source/index.html.md.erb

Prioritise describing the playbook as ‘internal’ over being in ‘alpha’, and consistently use the word ‘playbook’ rather than ‘manual’ in the header.

Clarify name and status

---

config.rb

Pretty URLs are when files are rewritten to directories so that you don’t see the file extension. For example, `foo.html` would be rewritten to `/foo/index.html` so that you can access it at `/foo/`.
Netlify is currently configured to [rewrite ‘pretty URLs’ as part of post-processing when building the site][1] but this isn’t currently happening when running locally using `bundle exec middleman serve`.
This means that links that work when the site is deployed don’t work locally. For example, a relative link `./core-values/` from `/how-we-work` fails because the page is at `how-we-work/core-values.html`.
Thankfully, [Middleman has this functionality built in][2] so it’s just a case of enabling it.
Once this has merged, we may want to disable Netlify’s post-processing of pretty URLs to …

Enable ‘pretty URLs’ when running locally

---

source/guides/how-to-be-an-epic-lead.html.md

- removes mentions of sprints
- adds content about ensuring the squad works together in new cycle format

Update Epic lead guide

---

source/how-we-work/contribution-model.html.md.erb

Some epics will cover a stage of the contribution model, and in those scenarios people might want to look at and review the model – to see what activities might happen and who gets involved.
This PR adds a heading to make that easier and give us a link we can share.

Add a heading to make it easier to view the model

---

source/guides/get-help-from-other-roles.html.md
source/support/products-we-support/index.html.md
source/what-we-do/index.html.md.erb

For the "get help with a frontend developer" content, I realised it would be helpful to have a page listing the products we support, so this is that!
[#69b02c6](https://github.com/alphagov/design-system-team-docs/pull/49/commits/69b02c6082e6628b359ce287eb7a2d0eaa9ad989) is the relevant commit. The rest are the aforementioned "get help" docs that have been merged.

Add details of maintained products

---

source/support/communicating-with-users/common-responses.html.md

https://deploy-preview-74--govuk-design-system-team-docs.netlify.app/support/communicating-with-users/common-responses/#making-gov-uk-frontend-work-with-javascript-frameworks
- reminds of the importance of progressive enhancement, linking to the Service Manual
- hints at how to integrate, highlighting possible caveats
- ask for feedback to help us design the future of our API

Add generic support message to help use GOV.UK Frontend with JS frameworks

---

source/community/code-of-conduct-for-workshops.html.md
source/community/index.html.md.erb

This is currently a Google doc on our drive. Having a web version makes it easier to access for workshop attendees

Add code of conduct for workshops

---

source/support/support-channels/index.html.md

2 commits for 2 changes:
1. Adds to the section on adding folks to x-gov slack for instances where the user's account has been deactivated, therefore `/invite` won't work
2. Fixes a broken link

Support slack section update

---

source/who-we-are/index.html.md.erb

As part of the offboarding process for Claire, I'm actioning Ollie's idea that our team page in our playbook should just link to the website page so we only have to keep one page up to date.

Update team page on team playbook

---

source/what-we-do/index.html.md.erb

The link isn’t referred to within the page content, so this isn’t used in the HTML output.

Remove unused email address from products page

---

source/support/communicating-with-users/common-responses.html.md
source/support/products-we-support/index.html.md

- Specify which versions of govuk-frontend are considered supported
- Add responses for possible support questions about new organisation colours
- Prettify common responses Markdown; this mostly modified whitespace usage in various parts of the document

Organisation colour support content updates

---

source/security/incidents.html.md

DSP is running a monthly incident report at which we should share any incident happening in our project. This PR adds a not so we don't miss that.

Add step for sharing incident at monthly incident report

---

source/design-and-content/content-ops.html.md.erb

As part of https://github.com/alphagov/design-system-team-internal/issues/932

Add 'content operations' guidance to team playbook

---

source/security/incidents.html.md

From a recent [incident review](https://docs.google.com/document/d/1me2r8YzZrGWWBnaKqx6wK7m2zki7-eycsQO0Ww3cWLs/edit?tab=t.0#heading=h.p99426yo0rbv).
Encourage video calls to mob on incidents.
Give further example of a P4 incident.

Update incident process
